## 실행 오류와 오류 처리

문법에 맞게 쓰여진 소스파일을 컴파일 하여 실행하더라도 프로그램에는 여러가지 이유 등에 의해 오류가 발생할 수 있다. 이러한 실행 오류는 크게 **논리가 잘못되었거나 예외에 대한 처리를 하지
 않은 경우**의 두 가지가 있다.
 
+ ### 논리 오류
   소스코드의 논리적인 부분이 잘못되어 의도치 않은 코드를 실행하거나 잘못된 값이 나오게 되는 것이다. 이 경우, 실행 중에 프로그램이 종료될 만큼 치명적이진 않으나 발견하기 힘들 수 
   있다는 점이 있다.
   
+ ### 예외 대처 실패
  문법과 논리가 정확히 작성되었지만, 컴파일 이후의 단계에서 데이터가 입력되는 과정 등에서 예기치 못한 오류가 발생할 수 있으며, 그 예로는 나눗셈의 연산에서 0을 나누게 되거나, 할당된
  공간보다 더 큰 데이터가 입력되는 등의 상황이 있다.
  

## 예외 상황에 대한 대처가 없는 경우
다음은 특정한 경우에 오류가 발생하여 의도치 않은 결과를 출력한 프로그램이다.
```c++
void func(int num) { 
	int a[5] = { 1,2,3,4,5 }; // 배열을 할당하고 초기화

	cout << "output : " << a[num] << endl; // 전달받은 num 값의 배열 인덱스를 출력
}
int main(int argc, const char* argv[]) {
	func(3);
	func(5); // 이상한 값 출력

	return 0;
}
```
```c++
4
-872382
```

위의 경우는 할당된 배열을 초과한 데이터를 출력하려해 발생한 오류이다. 해당 상황은 배열이 할당된 개수보다 큰 정수 값이 전달되는 예외를 처리하지 못했기 때문에 발생했다고 볼 수 있다.
따라서 이러한 오류를 발생시키지 않도록 func() 호출 과정에서 배열 할당 크기 이상의 값이 전달되지 않도록 해야하는 기능을 추가하여 이러한 오류를 방지할 필요가 있다.

+ ## 조건문과 리턴 값을 이용한 오류 처리
  조건문을 사용하여 특정 상황에 대한 리턴 값을 특정하여 오류를 걸러내는 방법이다. 다음의 코드는 위의 상황에서 배열 인덱스와 맞지 않은 값이 입력되었을 경우 오류 문구를
  출력하도록 한다.
  ```c++
  int func(int num) {
	if (num < 0 || num > 5) return -1; // num 값이 배열 인덱스 범위인 0~4가 아닐 경우 -1 리턴
	int a[5] = { 1,2,3,4,5 };

	return a[num]; // 정상적인 값 리턴
  }
  int main(int argc, const char* argv[]) {
	
	int v;
	v = func(3);  // 4를 리턴
	if (v != -1) cout << "vlaue : " << v << endl; // 리턴 값이 -1이 아닐 경우 정상 출력
	else cout << "value error" << endl;           // 리턴 값이 -1일 경우 오류 문구 출력

	v = func(-3); // -1을 리턴
	if (v != -1) cout << "vlaue : " << v << endl; // 리턴 값이 -1이 아닐 경우 정상 출력
	else cout << "value error" << endl;           // 리턴 값이 -1일 경우 오류 문구 출력

	return 0;
  }
  ```
  실행 결과
  ```c++
  vlaue : 4
  value error
  ```
  
+ ## 참조 매개 변수와 리턴 값을 이용한 오류 처리
  위의 조건문은 리턴 값이 정상 값과 오류 값을 함께 표현하여 코드의 수정이나 보수가 힘들 수 있다.
   다음과 같이 참조 매개 변수를 통해 결과 값을 따로 저장하여 오류의 구문을 위한 값과 구분할 수 있다.
   ```c++
   // 참과 거짓의 여부만 필요하므로 bool 형으로 선언
  bool func(int num, int& ref) { // 결과 값을 전달할 참조 변수 ref
	if (num < 0 || num > 5) return false; // num 값이 배열 인덱스 범위인 0~4가 아닐 경우 false 리턴
	int a[5] = { 1,2,3,4,5 };
	ref = a[num];

	return true; // true 리턴
  }
  int main(int argc, const char* argv[]) {
	
	int v = 0; // 결과 값을 저장할 변수 v

	// true를 리턴
	if (func(3, v) == true) cout << "vlaue : " << v << endl;
	else cout << "value error" << endl;

	// false를 리턴 
	if (func(-3, v) == true) cout << "vlaue : " << v << endl;
	else cout << "value error" << endl;

	return 0;
  }
  ```
  실행 결과
  ```c++
  vlaue : 4
  value error
  ```


  
  

  

   
   
